# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js image with Bun pre-installed
FROM jarredsumner/bun:latest

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container
COPY . .

# Install Wrangler globally
RUN bun install wrangler -g

# Install all dependencies specified in package.json
RUN bun install

# Expose the port the app runs on
EXPOSE 8787

# Start the MCP server in development mode
CMD ["bun", "dev"]
